# Spectral Feature Selection

Source: [Zheng Alan Zhao and Huan Liu. _Spectral Feature Selection for Data Mining_. CRC Press, 2012](https://library.oapen.org/viewer/web/viewer.html?file=/bitstream/handle/20.500.12657/25274/1004820.pdf?sequence=1&isAllowed=y)

In [1]:
import numpy as np

## Introduction

* Data mining refers to extracting nuggets of knowledge from data.
* Data has grown very large, both in number of observations and in dimensionality (number of features) in recent years.
* **The Curse of Dimensionality:** The more features in your model the less well it will fit, and the more time it will take to train.
* To avoid the curse of dimensionality, you need to reduce dimentions through what's known as dimensionality reduction techniques.

In [2]:
# Example of the Curse of dimensionality

### Dimensionality Reduction Techniques

* Dimensionality reduction techniques allow you to take out irrelevant (or barely relevant) information.
* General process:
    1. There is a scoring function, $r$, evaluates the renevance of the features given the data.
    2. A matrix $W$ is chosen to select or reduce data to the number of desired features.
    3. Features are then processed via the $W$ transform.
* There are two main approaches to dimentionality reduction: feature selection and feature extraction.
* It's sometimes useful to combine these approaches.

#### Feature Selection

* Remove (ignore) features in your data to only keep those that are relevant enough.
* Works by creating a **selection matrix**, $W$, that chooses which features to use.
* Uses already existing features.
* Really good when interpretability or knowledge extraction is required.
* Usually not as much predictive power as feature extraction.

**General formulation:**

Assuming dataset $X \in \mathbb{R}^{n \times m}$. The problem of feature selection can be formulated as

$$
\max_W r\left(\hat{X}\right) \\
s.t. \;\; \hat{X} = XW,\\
W \in \{0,1\}^{m \times q},\\
W^T \mathbf{1}^{m \times 1} =  \mathbf{1}^{q \times 1},\\
\left \| W \mathbf{1}^{q \times 1} \right \|_0 = q
$$

Note that the conditions imply that each column in $W$ has exactly one 1 and the remaining values are zeros.

Example:

In [10]:
X = np.array([[1, 7, 3], [5, 6, 4], [10, 9, 8]])
X

array([[ 1,  7,  3],
       [ 5,  6,  4],
       [10,  9,  8]])

In [12]:
W = np.array([[1, 0], [0, 0], [0, 1]])
W

array([[1, 0],
       [0, 0],
       [0, 1]])

In [11]:
np.matmul(X, W)

array([[ 1,  3],
       [ 5,  4],
       [10,  8]])

* There are feature selection schemes for supervised, unsupervised, and semi-supervised learning.
* There are three main strategies to evaluate feature relevance (compute $r$):
    1. **Filter strategy:**
        * **Basic idea:** choose the top $k$ features that best relate to the objective. This can mean:
            1. Correlation with target variable,
            2. Variance captured,
            3. Any other measure that relates the feature to your objective.
        * Generally (though not always) assumes feature relevances are independent.
        * _Backward elimination_: Start with many features and drop the least relevant ones.
        * _Forward elimination_: Start with few features and add the next most relevant ones.
        * Heuristics have been developed for low-order interactions.
        * Not biased towards a learner model, i.e. they stay the same for all models.
        * Simple structures with fast solutions.
        * High explainability, low performance.
    2. **Wrapper strategy:**
        * **Basic idea:** Features that provide better results in the model are more relevant.
        * Starts with a predetermined algorithm, and the score $r$ is computed by model performance under the selection matrix $W$.
        * Also uses forward and backward elimination.
        * Heuristics have been developed to optimize the solution because models usually train non-linearly, making evaluation non-linear.
    3. **Embedded strategy:**
        * **Basic idea:** Let the model tell you what's relevant during training.
        * Feature selection is incorporated in the training phase.
        * Generally uses $L_1$ regularization.
        * Usually more efficient than the wrapper strategy.
        
* Challenges of feature selection:
    * **Redundant features:** Features that are relevant to the problem, while causing no ill-effect due to their removal.
    * Several feature selection schemes aren't well prepared to deal with terabyte volumes of data.
    * Most feature selection algorithms only work with structured data.
    * Feature selection algorithms tend to fail when using small sample sizes.

#### Feature Extraction

* Combine already available information from features and condense them into a lower number of features.
* Works by creating a **weight matrix**, $W'$, that combines the features.
* Creates new features.
* Creates features with more predictive power.
* Looses interpretability.

### Spectral Feature Selection

* General and unified framework that encompasses algorithms for both feature selection and extraction.
* Allows us to create novel techniques, specifically designed for a particular problem.
* **Basic idea:** Identify features that associate similar values with samples of the same affiliation.
* Measures relevance by the feature's capability of preserving pre-specified sample similarity by measuring their consistency with the spectrum of a matrix derived from a similarity matrix of the samples ($S$).

In [13]:
# Example of Spectral Feature Selection?

## Univariate Formulations for Spectral Feature Selection.

### Def:

Let $N$ denote the number of samples and $(x_i)_{i = 1}^{N}$ the vector of observed values. The **pairwise sample similarity** between $x_i$ and $x_j$, denoted by $s_{ij}$, is a non-negative funciton that measure of how similar two samples are.

* For unlabeled data, we can define a $\delta > 0$ and use the Gaussian radial basis function (RBF):

$$
s_{ij} = exp \left( - \; \frac{ \left\| x_i - x_j \right\| ^2}{2 \delta ^2} \right)
$$

* For labeled data, if $n_l$ denotes the number of samples in class $l$, we can use:

$$
s_{ij} = \left\{\begin{matrix}
\frac{1}{n_l}, & y_i = y_j = l\\ 
0 & \mbox{otherwise}
\end{matrix}\right. .
$$

### Def:

Let $N$ denote the number of samples. Then, given a pairwise similarity measure, $s_{ij}$, we define the **similarity matrix** as:

$$
S := S_{ij} = (s_{ij})
$$

Additionally, if $S$ has a positive semi-definite submatrix, it's called a **kernel matrix**.

### Note:

Let $S$ be a similarity matrix of a sample. It is possible to construct a fully connected undirected graph, $G(V, E)$, where vertex $v_i$ corresponds to sample $x_i$ and $S$ is its adjacency matrix.

### Def:

Let $G(V, E)$ be a graph with adjacency matrix $S=(s_{ij})$. The **degree matrix** of graph $G$ is the diagonal matrix constructed as

$$
D := D(i, j) = \left\{\begin{matrix}
d_i, & i = j\\ 
0 & \mbox{otherwise}
\end{matrix}\right. ,
$$

where

$$
d_i = \displaystyle\sum_{k=1}^{N}s_{ik}.
$$

### Note:

Using the notation from the previous definition, $d_i$ can be interpreted as an estimation of the density around sample $x_i$.

### Def:

Let $G$ be a graph with adjacency matrix $S$ and degree matrix $D$. The **Laplacian matrix** of $G$, denoted by $L$, is defined as:

$$
L := D - S
$$

Moreover, the **normalized Laplacian matrix** of $G$, denoted by $\mathcal{L}$, is defined as:

$$
\mathcal{L} := D^{-\frac{1}{2}} L D^{-\frac{1}{2}}
$$